version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "posthog-js"
    labels:
      - "dependencies"
      - "posthog"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 2
